execUserReset()
{

 __message("-I- execUserReset");
__writeMemory32(0x000000E0,  0xE0042004, "Memory"); //DBGMCU_CR enable trace clock and ports
__writeMemory32(0x00000010,  0x40023830, "Memory"); //Enable GPIOE  clock
__writeMemory32(0x00002AA0,  0x40021000, "Memory"); //Configure PE2, PE3, PE4, PE5, and PE6 as AF
__writeMemory32(0x00001550,  0x4002100C, "Memory"); // Configure GPIOE as pull-up
__writeMemory32(0x00003FF0,  0x40021008, "Memory"); // Configure GPIOE speed as 100Mhz
__writeMemory32(0x00000000,  0x40021020, "Memory"); //Enable AF0 in GPIOE_AFRL register

}