/**********************************************************************
* $Id$		sct_fsm.c			2011-06-02
*//**
* @file		sct_fsm.c
* @brief	This file contains function initialize SCT module
* @version	1.0
* @date		02. June. 2011
* @author	NXP MCU SW Application Team
*
* Copyright(C) 2011, NXP Semiconductor
* All rights reserved.
*
***********************************************************************
* Software that is described herein is for illustrative purposes only
* which provides customers with programming information regarding the
* products. This software is supplied "AS IS" without any warranties.
* NXP Semiconductors assumes no responsibility or liability for the
* use of the software, conveys no license or title under any patent,
* copyright, or mask work right to the product. NXP Semiconductors
* reserves the right to make changes in the software without
* notification. NXP Semiconductors also make no representation or
* warranty that such application will be suitable for the specified
* use without further testing or modification.
* Permission to use, copy, modify, and distribute this software and its
* documentation is hereby granted, under NXP Semiconductors'
* relevant copyright in the software, without fee, provided that it
* is used in conjunction with NXP Semiconductors microcontrollers.  This
* copyright, permission, and disclaimer notice must appear in all copies of
* this code.
**********************************************************************/
/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

/* Uses following resources: */
/* [5 events, 5+0 states, 0 inputs, 4 outputs, 1 match regs, 0 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{

/* MATCH/CAPTURE registers */
LPC_SCT->REGMODE_L = 0x0000;         /* L: 1x MATCH, 0x CAPTURE, 15 unused */
LPC_SCT->REGMODE_H = 0x0000;             /* H: 0x MATCH, 0x CAPTURE, 16 unused */
LPC_SCT->MATCH_L[0] = speed;
LPC_SCT->MATCHREL_L[0] = speed;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0;        /* CTOUT0 */
LPC_SCT->OUT[0].CLR = 0;
LPC_SCT->OUT[1].SET = 0;        /* CTOUT1 */
LPC_SCT->OUT[1].CLR = 0;
LPC_SCT->OUT[2].SET = 0;        /* CTOUT2 */
LPC_SCT->OUT[2].CLR = 0;
LPC_SCT->OUT[3].SET = 0;        /* CTOUT3 */
LPC_SCT->OUT[3].CLR = 0;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[4].SET = 0x00000010;
LPC_SCT->OUT[4].CLR = 0x00000001;
LPC_SCT->OUT[5].SET = 0x00000001;
LPC_SCT->OUT[5].CLR = 0x10000010;
LPC_SCT->OUT[6].SET = 0;
LPC_SCT->OUT[6].CLR = 0;
LPC_SCT->OUT[7].SET = 0;
LPC_SCT->OUT[7].CLR = 0;
LPC_SCT->OUT[8].SET = 0;
LPC_SCT->OUT[8].CLR = 0;
LPC_SCT->OUT[9].SET = 0;
LPC_SCT->OUT[9].CLR = 0;
LPC_SCT->OUT[10].SET = 0;
LPC_SCT->OUT[10].CLR = 0;
LPC_SCT->OUT[11].SET = 0;
LPC_SCT->OUT[11].CLR = 0;
LPC_SCT->OUT[12].SET = 0;
LPC_SCT->OUT[12].CLR = 0;
LPC_SCT->OUT[13].SET = 0;
LPC_SCT->OUT[13].CLR = 0;
LPC_SCT->OUT[14].SET = 0;
LPC_SCT->OUT[14].CLR = 0;
LPC_SCT->OUT[15].SET = 0;
LPC_SCT->OUT[15].CLR = 0;
LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x0000000F) | 0x00000000;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x0001D000;     /* L: --> state CTOUT0_high */
LPC_SCT->EVENT[0].STATE = 0x00000001;
LPC_SCT->EVENT[1].CTRL = 0x00005000;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[1].STATE = 0x00000002;
LPC_SCT->EVENT[2].CTRL = 0x00025000;     /* L: --> state CTOUT1_high */
LPC_SCT->EVENT[2].STATE = 0x00000008;
LPC_SCT->EVENT[3].CTRL = 0x0000D000;     /* L: --> state CTOUT3_high */
LPC_SCT->EVENT[3].STATE = 0x00000004;
LPC_SCT->EVENT[4].CTRL = 0x00015000;     /* L: --> state CTOUT2_high */
LPC_SCT->EVENT[4].STATE = 0x00000010;
  /* Unused events must not have any effect */
LPC_SCT->EVENT[5].STATE = 0;
LPC_SCT->EVENT[6].STATE = 0;
LPC_SCT->EVENT[7].STATE = 0;
LPC_SCT->EVENT[8].STATE = 0;
LPC_SCT->EVENT[9].STATE = 0;
LPC_SCT->EVENT[10].STATE = 0;
LPC_SCT->EVENT[11].STATE = 0;
LPC_SCT->EVENT[12].STATE = 0;
LPC_SCT->EVENT[13].STATE = 0;
LPC_SCT->EVENT[14].STATE = 0;
LPC_SCT->EVENT[15].STATE = 0;

/* STATE registers */
LPC_SCT->STATE_L = 0;
LPC_SCT->STATE_H = 0; /* implicit value */

/* state names assignment: */
  /* State L 0: L_ENTRY */
  /* State L 1: CTOUT3_high */
  /* State L 2: CTOUT2_high */
  /* State L 3: CTOUT0_high */
  /* State L 4: CTOUT1_high */

/* CORE registers */
LPC_SCT->START_L = 0x0000;
LPC_SCT->STOP_L =  0x0000;
LPC_SCT->HALT_L =  0x0000;
LPC_SCT->LIMIT_L = 0x0000;
LPC_SCT->START_H = 0x0000;
LPC_SCT->STOP_H =  0x0000;
LPC_SCT->HALT_H =  0x0000;
LPC_SCT->LIMIT_H = 0x0000;
LPC_SCT->EVEN =    0x00000000;
LPC_SCT->DMA0REQUEST = 0x00000000;
LPC_SCT->DMA1REQUEST = 0x00000000;

}
