/**********************************************************************
* $Id$		sct_fsm.h			2011-06-02
*//**
* @file		sct_fsm.h
* @brief	Contains all macro definitions and function prototypes
* 			support for initialize SCT FSM module
* @version	1.0
* @date		02. June. 2011
* @author	NXP MCU SW Application Team
*
* Copyright(C) 2011, NXP Semiconductor
* All rights reserved.
*
***********************************************************************
* Software that is described herein is for illustrative purposes only
* which provides customers with programming information regarding the
* products. This software is supplied "AS IS" without any warranties.
* NXP Semiconductors assumes no responsibility or liability for the
* use of the software, conveys no license or title under any patent,
* copyright, or mask work right to the product. NXP Semiconductors
* reserves the right to make changes in the software without
* notification. NXP Semiconductors also make no representation or
* warranty that such application will be suitable for the specified
* use without further testing or modification.
* Permission to use, copy, modify, and distribute this software and its
* documentation is hereby granted, under NXP Semiconductors'
* relevant copyright in the software, without fee, provided that it
* is used in conjunction with NXP Semiconductors microcontrollers.  This
* copyright, permission, and disclaimer notice must appear in all copies of
* this code.
**********************************************************************/
#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init(void);

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_CTOUT0 (0)
#define SCT_OUTPUTPRELOAD_CTOUT0 (0)
#define SCT_OUTPUT_CTOUT1 (1)
#define SCT_OUTPUTPRELOAD_CTOUT1 (0)
#define SCT_OUTPUT_CTOUT2 (2)
#define SCT_OUTPUTPRELOAD_CTOUT2 (0)
#define SCT_OUTPUT_CTOUT3 (3)
#define SCT_OUTPUTPRELOAD_CTOUT3 (0)


/* Match register reload macro definitions */
#define reload_maxcount(value) LPC_SCT->MATCHREL_L[0] = value;

#endif
